/*
 * Web
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.Runtime.Serialization;

namespace ReleaseApp.Updater.Model
{
    /// <summary>
    /// Defines AppArch
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum AppArch
    {
        /// <summary>
        /// Enum Win32 for value: Win32
        /// </summary>
        [EnumMember(Value = "Win32")]
        Win32 = 1,

        /// <summary>
        /// Enum Win64 for value: Win64
        /// </summary>
        [EnumMember(Value = "Win64")]
        Win64 = 2,

        /// <summary>
        /// Enum LinuxDeb for value: LinuxDeb
        /// </summary>
        [EnumMember(Value = "LinuxDeb")]
        LinuxDeb = 3,

        /// <summary>
        /// Enum LinuxRpm for value: LinuxRpm
        /// </summary>
        [EnumMember(Value = "LinuxRpm")]
        LinuxRpm = 4,

        /// <summary>
        /// Enum LinuxSnap for value: LinuxSnap
        /// </summary>
        [EnumMember(Value = "LinuxSnap")]
        LinuxSnap = 5

    }

}