// import { ConfigModule } from "@main/modules/config/config.module";
// import { ConfigMigrationModule } from "@main/modules/config/config.migration.module";
// import { MainContextModule } from "@main/modules/context/main.context.module";
// import { RequestInterceptionModule } from "@main/modules/request/interception.request.module";
// import { WindowModule } from "@main/modules/window/window.module";
// import { WindowPositionModule } from "@main/modules/window/window.position.module";
// import { DeeplinkModule } from "@main/modules/deeplink.module";
// import { FileModule } from "@main/modules/file.module";
// import { IpcModule } from "@main/modules/ipc.module";
// import { ProcessModule } from "@main/modules/process.module";
// import { ShortcutModule } from "@main/modules/shortcut.module";
// import { TrayIconModule } from "@main/modules/trayicon.module";
// import { UpdateModule } from "@main/modules/update.module";
// import { container } from "@main/di/container.di";
//
// // container.bind(MainContextModule).toSelf();
// // container.bind(ConfigModule).toSelf();
// // container.bind(ConfigMigrationModule).toSelf();
// // container.bind(RequestInterceptionModule).toSelf();
// // container.bind(WindowModule).toSelf();
// // container.bind(WindowPositionModule).toSelf();
// // container.bind(DeeplinkModule).toSelf();
// // container.bind(FileModule).toSelf();
// // container.bind(IpcModule).toSelf();
// // container.bind(ProcessModule).toSelf();
// // container.bind(ShortcutModule).toSelf();
// // container.bind(TrayIconModule).toSelf();
// // container.bind(UpdateModule).toSelf();
