import { Container } from "inversify";
import { ProcessService } from "../common/process.service";
import { DialogService } from "../electron/dialog.service";
import { WindowService } from "../electron/window.service";
import { MediaService } from "../media/media.service";
import { TorrentService } from "../media/torrent.service";
import { SystemService } from "../system/system.service";
import { FilesService } from "../files/files.service";
import { ConfigurationService } from "../configuration/configuration.service";
import { GithubService } from "../projects/github.service";
import { FeatureService } from "../projects/feature.service";
import { DockerService } from "../projects/docker.service";
import { OpenvpnService } from "../network/openvpn.service";
import { NordvpnService } from "../network/nordvpn.service";

export const container = new Container({ defaultScope: "Singleton" });
container.bind(ProcessService).toSelf();
container.bind(DialogService).toSelf();
container.bind(WindowService).toSelf();
container.bind(MediaService).toSelf();
container.bind(TorrentService).toSelf();
container.bind(SystemService).toSelf();
container.bind(FilesService).toSelf();
container.bind(ConfigurationService).toSelf();
container.bind(GithubService).toSelf();
container.bind(FeatureService).toSelf();
container.bind(DockerService).toSelf();
container.bind(OpenvpnService).toSelf();
container.bind(NordvpnService).toSelf();
